# Generated by Django 2.0 on 2017-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171220_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='filtered',
            field=models.ImageField(blank=True, upload_to='app/static/filtered_pictures/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='app/static/pictures/'),
        ),
    ]
