# Generated by Django 2.0 on 2018-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_imagemodel_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='../app/static/pictures'),
        ),
    ]
