# Generated by Django 2.0.1 on 2018-01-31 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180130_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
