# Generated by Django 2.0.1 on 2018-01-30 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180130_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='uploaded_by',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
