# Generated by Django 2.0.1 on 2018-01-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180131_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='uploaded_by',
            new_name='commentor',
        ),
    ]
